name: Deploy Frontend on SUSE Self-Hosted Runner

on:
  push:
    branches:
      - main  # adjust if needed

jobs:
  deploy:
    runs-on: self-hosted  # your SUSE GitHub runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.local
          echo "PORT=3001" >> .env.local

      - name: Install dependencies
        run: npm install
 
      - name: Build the app
        run: npm run build

      - name: Free up port 3001 (kill if in use)
        run: |
          echo "Killing any process using port 3001..."
          lsof -t -i:3001 | xargs -r kill -9 || true

      - name: Start frontend with PM2
        run: |
          pm2 delete frontend || true
          pm2 start npm --name "frontend" -- run start
        env:
          PORT: 3001
