name: Deploy Frontend on SUSE Self-Hosted Runner

on:
  push:
    branches:
      - main  # or the branch you deploy from

jobs:
  deploy:
    runs-on: self-hosted  # runs on your SUSE server

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.local
          # Add more if needed

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Start the frontend app
        run: npm run start
